<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 8</b></center>    
<left><b><h3>Roll No. : 111</b></left>  
<left><b><h3>Name : Dhara</b></left>   
<pre>    

### 1. import numpy library.

In [1]:
import numpy as np

### 2.Create an array of 10 zeros

In [2]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 3. Create an array of 10 ones.


In [3]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 4. Create an array of 10 fives

In [4]:
print(np.full(10, 5))

[5 5 5 5 5 5 5 5 5 5]


### 5. Create an array of integers from 10 to 50.

In [5]:
print(np.arange(10, 51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 6. Create an array of all the even integers from 10 to 50.

In [6]:
print(np.arange(10, 51, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [7]:
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Create a 3x3 identity matrix.

In [8]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 9. Use Numpy to generate a random number between 0 and 1


In [9]:
print(np.random.rand())

0.7805854170542816


### 10. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [10]:
print(np.random.randn(25))

[-0.93844195  1.3223431  -0.12042212 -0.13327516 -1.0452298   0.22507651
 -2.00390552  0.59983835  0.29420393 -0.65297752  2.25313795 -0.91518061
  1.09865065  0.92361313 -1.73410482  0.57499933  0.04665246  0.37916231
  0.10967248 -2.08761967 -0.3193682  -1.07495095 -1.04178092  2.08070052
  0.70429462]


### 11. Create linspace array

In [11]:
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


### 12. Create an array of 20 linearly spaced points between 0 and 1. 

In [12]:
print(np.linspace(0, 1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### 13. Create Random Integer Array

In [13]:
print(np.random.randint(1, 100, 10))

[ 1 75 42 27 32 91 58 97 93 49]


### 14. Create Random Integer Array and Reshape that Array

In [14]:
arr = np.random.randint(1, 100, 12).reshape(3, 4)
print(arr)

[[56  9 98 60]
 [15 57 10 94]
 [39 81 73  8]]
